---
title: "Mutagenesis Protocol"
author: "generated by GoldenMutagenesisWeb - https://msbi.ipb-halle.de/GoldenMutagenesisWeb"
date: "`r format(Sys.time(), '%d %B, %Y - %H:%M:%S')`"
header-includes:
 \input{analysis.sty}
output:
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
    includes:
        in_header: analysis.sty
subparagraph: yes
geometry: "a4paper,left=2.5cm,right=2.5cm,top=3.5cm,bottom=3cm,headheight=39pt,footskip=2cm"
params:
  path: NA
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
#library(kableExtra)
load(params$path)
```
\renewcommand{\DNAblock}{40} 
# Legend
```{=latex}
{\LARGE
\DNA !  '{prefix}Prefix'{re}RestrictionEnzyme'{suffix}Suffix'{vector}Vector'{overhang}Overhang'{extra}Extra'{bs}BindingSequence !
}
```
\renewcommand{\DNAblock}{40} 
# Fragments and Primer
```{r echo=FALSE, eval=TRUE, include=FALSE}
out <- NULL

for (i in 1:length(primers@fragments)) {
      env=new.env() #create a new empty environment, it inherits objects from the current environment.
      out <- c(out,knit_child('primer_subunit.Rmd', envir=env))
}
```
`r  paste(out, collapse='\n')`
